/**
 * Shared TypeScript types for the GameEval QA Pipeline
 * 
 * Environment bindings (Env interface) are auto-generated by wrangler types
 * See worker-configuration.d.ts for the full Env interface
 * 
 * Add custom application types here as needed for future stories
 */

import type { Phase, LogType } from './constants';

// Database result types (Story 1.2)

/**
 * TestRun represents a test execution in the database
 */
export interface TestRun {
  id: string;
  url: string;
  input_schema: string | null;
  status: string;
  overall_score: number | null;
  created_at: number;
  updated_at: number;
  completed_at: number | null;
}

/**
 * EvaluationScore represents a single metric score for a test run
 */
export interface EvaluationScore {
  id: number;
  test_run_id: string;
  metric_name: string;
  score: number;
  justification: string;
  created_at: number;
}

/**
 * TestEvent represents a logged event during test execution
 */
export interface TestEvent {
  id: number;
  test_run_id: string;
  phase: string;
  event_type: string;
  description: string;
  timestamp: number;
  metadata?: string; // Optional JSON string for AI request metadata (model, cost, tokens)
}

/**
 * Generic database result wrapper for error handling
 */
export type DbResult<T> = 
  | { success: true; data: T }
  | { success: false; error: string };

// R2 Storage types (Story 1.3)

/**
 * Metadata extracted from screenshot paths
 */
export interface ScreenshotMetadata {
  /** Test pipeline phase (phase1-phase4) */
  phase: Phase;
  /** Action description (e.g., 'click-play-button') */
  action: string;
  /** Screenshot timestamp (Unix epoch in milliseconds) */
  timestamp: number;
}

/**
 * Screenshot artifact stored in R2 with parsed metadata
 */
export type ScreenshotArtifact = {
  /** R2 object key (full path) */
  key: string;
  /** Artifact discriminator */
  type: 'screenshot';
  /** Public URL for accessing the artifact */
  url: string;
  /** Upload timestamp (Unix epoch in milliseconds) */
  uploaded_at: number;
  /** Parsed metadata extracted from the object key */
  metadata: ScreenshotMetadata;
};

/**
 * Log artifact stored in R2 with parsed metadata
 */
export type LogArtifact = {
  /** R2 object key (full path) */
  key: string;
  /** Artifact discriminator */
  type: 'log';
  /** Public URL for accessing the artifact */
  url: string;
  /** Upload timestamp (Unix epoch in milliseconds) */
  uploaded_at: number;
  /** Parsed metadata extracted from the object key */
  metadata: {
    logType: LogType;
  };
};

/**
 * Represents a test artifact stored in R2
 */
export type TestArtifact = ScreenshotArtifact | LogArtifact;

// AI Gateway types (Story 1.5)

/**
 * AI model preference for routing
 */
export type ModelPreference = 'primary' | 'fallback';

/**
 * Token usage information from AI requests
 */
export interface TokenUsage {
  input?: number;
  output?: number;
  total?: number;
}

/**
 * AI request metadata for observability
 */
export interface AIMetadata {
  model: string;
  provider: 'workers-ai' | 'openai' | 'anthropic';
  cached?: boolean;
  cost?: number;
  tokens?: TokenUsage;
  latency_ms?: number;
  test_run_id?: string;
  user_id?: string;
  [key: string]: unknown; // Allow additional custom metadata
}

/**
 * Standardized AI response from callAI() helper
 */
export interface AIResponse {
  text: string;
  model: string;
  provider: 'workers-ai' | 'openai' | 'anthropic';
  cost?: number;
  cached?: boolean;
  tokens?: TokenUsage;
  metadata?: AIMetadata;
}

// TestAgent Durable Object types (Story 2.1)

/**
 * Metadata for evidence stored in R2
 */
export interface EvidenceMetadata {
  /** Evidence type (screenshot or log) */
  type: 'screenshot' | 'log';
  /** Public R2 URL for accessing the evidence */
  url: string;
  /** Timestamp when evidence was stored (Unix epoch in milliseconds) */
  timestamp: number;
  /** Optional description of the evidence */
  description?: string;
}

/**
 * Result from a phase execution
 */
export interface PhaseResult {
  /** Whether the phase succeeded */
  success: boolean;
  /** Optional message describing the result */
  message?: string;
  /** Optional data returned from the phase */
  data?: Record<string, unknown>;
}

/**
 * Phase 1 specific result structure (Story 2.3)
 */
export interface Phase1Result {
  /** Whether Phase 1 succeeded */
  success: boolean;
  /** Whether game requires user interaction to start */
  requiresInteraction: boolean;
  /** Error messages if any validation failed */
  errors: string[];
}

/**
 * Control map for discovered interactive elements (Story 2.4)
 */
export type ControlMap = {
  [selector: string]: {
    /** Type of control interaction */
    type: 'click' | 'keyboard' | 'drag' | 'hover';
    /** Human-readable description of the control */
    description: string;
  };
};

/**
 * Phase 2 specific result structure (Story 2.4)
 */
export interface Phase2Result {
  /** Whether Phase 2 succeeded */
  success: boolean;
  /** Map of discovered interactive controls */
  controls: ControlMap;
  /** Control hypothesis describing discovered controls */
  hypothesis: string;
}

/**
 * Browser session handle stored in DO state
 */
export interface BrowserSessionHandle {
  /** Unique browser session ID */
  handle: string;
  /** Timestamp when session was created (Unix epoch in milliseconds) */
  createdAt: number;
  /** Timestamp of last session access (Unix epoch in milliseconds) */
  lastUsed: number;
}

/**
 * Console log entry captured from browser
 */
export interface ConsoleLogEntry {
  /** Timestamp when log was captured (Unix epoch in milliseconds) */
  timestamp: number;
  /** Console log level (log, warn, error, info, debug) */
  level: string;
  /** Log message text */
  text: string;
}

/**
 * Network error tracked during test execution
 */
export interface NetworkError {
  /** Timestamp when error occurred (Unix epoch in milliseconds) */
  timestamp: number;
  /** URL that failed */
  url: string;
  /** HTTP status code if applicable */
  status?: number;
  /** Error description */
  error: string;
}

/**
 * TestAgent Durable Object state structure
 */
export interface TestAgentState {
  /** Test run UUID */
  testRunId: string;
  /** URL of the game being tested */
  gameUrl: string;
  /** Optional JSON schema for test guidance */
  inputSchema?: string;
  /** Evidence collected during test execution */
  evidence: EvidenceMetadata[];
  /** Results from each phase */
  phaseResults: Record<string, PhaseResult>;
  /** Browser session handle for persistence across phases */
  browserSession?: BrowserSessionHandle;
  /** Console logs captured from browser */
  consoleLogs: ConsoleLogEntry[];
  /** Network errors tracked during test execution */
  networkErrors: NetworkError[];
}

