/**
 * Shared TypeScript types for the GameEval QA Pipeline
 * 
 * Environment bindings (Env interface) are auto-generated by wrangler types
 * See worker-configuration.d.ts for the full Env interface
 * 
 * Add custom application types here as needed for future stories
 */

// Placeholder for future custom types
export {};

